### ISSUE TITLE
Order filtering by attributes

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/digicert#100]
@abunashir , we actually just ran into this issue today with one of our certificates expired.

In Digicert, a renewed order will have a different order ID from the original one. This means that we shouldn't hard code an order ID in generation.

It is useful in this case to allow fetching / filtering orders by:

* common name
* expiry date
* product type

Given this function we can perform the following without :
``` ruby
order = Digicert::Order.filter(
  common_name: "*.example.com", 
  product_type: Digicert::Product::WildcardSsl
).first
duplicate_request = order.duplicate
```

**Comment by abunashir** [comment]
Digcert does not provide any direct interface to filter orders by attributes, but as a patch, we can retrieve the orders and then apply the required filtering options like we are doing for the CLI gem here https://github.com/riboseinc/digicert-cli/commit/6731e3679ed0e44cc7589f00ee97d27c498a4753

**Comment by ronaldtse** [comment]
@abunashir just got this message from Digicert Product Manager Clint Wilson. We can now implement filtering properly! 👍 


> A lot of the GET endpoints can be filtered, but probably the most useful are the Orders List and Requests List. When you log into the web UI of CertCentral, everything you do is going through the API. So, the filters available should be somewhat familiar from the “Advanced” search options on the Orders List and the dropdown selections on the Requests List.
> 
> For example, querying for all Revoked Standard SSL certificates in the Division with id 12345, the request would be a GET to
>                `https://www.digicert.com/services/v2/order/certificate?container_id=12345&limit=25&offset=0&sort=-valid_till&filters%5Bstatus%5D=revoked&filters%5Bproduct_name_id%5D%5B0%5D=ssl_plus`
> 
> The other URL parameters that can be used are:

```
GET /order/certificate
               
container_id=
organization_id=
user_id=
filters[date_created]=
                =2017-05-10+00:00:00...2017-05-11+23:59:59
                >2017-01-01
filters[valid_till]
                =2017-05-10+00:00:00...2017-05-11+23:59:59
                <2017-05-11
filters[status]=
                issued
                pending
                processing
                reissue_pending
                reissue_processing
                revoked
                rejected
filters[search]=
                %mydomain.com
                %12345678
filters[common_name]=
                %mydomain.com
filters[product_name_id]=ssl_plus
                Multiple params can be passed in using array identifiers, like so: filters[product_name_id][0]=ssl_plus&filters[product_name_id][1]=ssl_multi_domain&filters[product_name_id][2]=ssl_wildcard
                Parameter values should be one of the “products.name_id” values from GET /product
limit=25
                (Max 1000)
offset=0
sort=
                %2Border_id
                -order_id
                %2Bdate_created
                -date_created
                %2Bcommon_name
                -common_name
                %2Bstatus
                -status
                %2Bvalidity_years
                -validity_years
                %2Bproduct_name
                -product_name
                %2Bvalid_till
                -valid_till
```

**Comment by ronaldtse** [comment]
Thanks @abunashir ! Looking nice and hope we can settle the "status" filtering issue soon.

**Comment by abunashir** [comment]
@ronaldtse: The filters are working fine for most of the attributes, except if we try to filter by `issued` or `expired` status, in both cases, it returns `issued` and `expired` orders together.

Reqeust with details:

<img width="937" alt="screenshot 2017-06-13 13 43 58" src="https://user-images.githubusercontent.com/1220911/27069316-628c7a06-503e-11e7-8b85-4d25d608517d.png">

Response [id, status, common_name]:

<img width="602" alt="screenshot 2017-06-13 13 45 03" src="https://user-images.githubusercontent.com/1220911/27069374-9a958302-503e-11e7-9c6e-9153e1c794ec.png">

Note: Filter by `expired` status is not listed int the provided doc.

cc: @clintwilson

**Comment by clintwilson** [comment]
`expired` isn't a status stored with orders. Instead, at least in our UI, we filter based off `valid_till` to filter out expired. So, to find only issued or "in progress" orders which also haven't expired yet, you could do:
https://www.digicert.com/services/v2/order/certificate?sort=%2Dorder_id&filters%5Bstatus%5D%5B0%5D=issued&filters%5Bstatus%5D%5B1%5D=pending&filters%5Bstatus%5D%5B2%5D=processing&filters%5Bvalid_till%5D%5B0%5D=>2017-06-13&filters%5Bvalid_till%5D%5B1%5D=0000-00-00&filters%5Bvalid_till%5D%5B2%5D=null

**Comment by ronaldtse** [comment]
Thanks @clintwilson for the clarification!

It's indeed a little misleading that the endpoint returns `status: expired` but it cannot be filtered as such. It would be better if those certificates just return `status: issued` instead for consistency, so it is clear that filtering for expiry should be based on `valid_till`.

Moving forward, @abunashir , I think we should implement a separate filter for searching expired orders since the filter combo is quite hard to read?

**Comment by abunashir** [comment]
@ronaldtse: Sure, should we implement that in the gem or the CLI?

**Comment by ronaldtse** [comment]
@abunashir as we discussed today, filtering by `expired` is already possible in the gem using the following syntax (using the same example earlier from @clintwilson):

```ruby
Digicert::Order.all(
  sort: '+order_id', 
  filters: {
    status: { '0' => 'issued', '1' => 'pending, '2' => 'processing' },
    # the '0000-00-00' and 'null' bits seem unnecessary
    valid_till: { '0' => '>2017-06-13' }
  }
)
```

If we can allow this it would be even better:
``` ruby
Digicert::Order.all(
  sort: '+order_id', 
  filters: {
    status: %w(issued pending processing),
    valid_till: %w(>2017-06-13)
  }
)
```

**Comment by clintwilson** [comment]
The '0000-00-00' and 'null' are used so that Orders in the states of Pending and Processing (which don't have actual valid_till values yet) are included in the returned report. They're optional, but useful to make the filter work with all 3 statuses.
