### ISSUE TITLE
Getting Digicert::Errors::ServerError when calling Digicert::Order.all

### ISSUE THREAD

**Issue by ramanbuttar** [riboseinc/digicert#134]
I am calling `Digicert::Order.all(sort: :expires_at)` and getting the following error:

`Digicert::Errors::ServerError: [{"code"=>"internal_error", "message"=>"An internal error has occurred processing your request."}]`

If I hit the Digicert API endpoint directly at https://www.digicert.com/services/v2/documentation/order/order-list, then there are no errors.

Looks like this gem is encountering some unexpected results from the Digicert API endpoint.

**Comment by ronaldtse** [comment]
@ramanbuttar thank you for letting us know. In any case, I don't think the API shouldn't be returning an internal error.

@abunashir could you have a look at this? Once we know the exact parameters that cause this we can report back to Digicert.

**Comment by abunashir** [comment]
Hi @ramanbuttar, the supported sort parameters are bit different than the usual response structure, and I think that's why it's returning a server error. To sort by expiring date you can use the following:

```ruby
Digicert::Order.all(sort: "+valid_till")
```

Supported values are `+valid_till`, `-valid_till`, but you can check [all others options here][1], Thanks!

cc: @ronaldtse 

[1]: https://github.com/riboseinc/digicert/issues/100#issuecomment-300707252

**Comment by ronaldtse** [comment]
@abunashir could we put Clint’s list in the README (and maybe some validation in our code) to resolve future questions?

In addition, let’s find out what parameters caused the 500 error. Clint’s team will want to know that. Thanks!

**Comment by abunashir** [comment]
Sure thing @ronaldtse, should we create a wiki page or you would prefer to put that in the readme?

**Comment by ronaldtse** [comment]
Just the README is easier. Thanks!

**Comment by ramanbuttar** [comment]
Thanks guys. `Digicert::Order.all(sort: "+valid_till")` worked just fine.

**Comment by ronaldtse** [comment]
Thanks @ramanbuttar for following up!
