### ISSUE TITLE
Digicert::DuplicateCertificateFinder.find_by doesn't work as expected

### ISSUE THREAD

**Issue by kwkwan** [riboseinc/digicert#137]
```
Digicert::DuplicateCertificateFinder.find_by(request_id: request_id)
```

Is supposed to return the certificate object. The API request and responses are correct, however `nil` is returned instead.

```ruby
[URI] GET https://www.digicert.com/services/v2/order/certificate/123/duplicate
[Headers] {"content-type"=>["application/json"], "x-dc-devkey"=>["XXX"], "host"=>["www.digicert.com"]}
[Response] #<Net::HTTPOK 200 OK readbody=true>
[Response Body] {"certificates":[{"id":}, {...}]}

# => `nil`
```

**Comment by ronaldtse** [comment]
@abunashir could you help fix this? Thanks!

**Comment by abunashir** [comment]
Thanks, @kwkwan for reporting this one, looks like there were some changes on the `date_created` field and that's why the finder could not find the certificate. Please have a look on the attached PR for more details, thanks!

**Comment by ronaldtse** [comment]
Thanks @abunashir !
