### ISSUE TITLE
Did we update the `order` response recently?

### ISSUE THREAD

**Issue by abunashir** [riboseinc/digicert#146]
Hi @ronaldtse, I was testing out the order duplication and reissuing funcitonality recently, but looks lik there might be some changes in the order response. For example, the order response does not include the `certificate.server_platform` related details anymore, could you please erify those changes so I can update the client?

Expected one:

<img width="648" alt="screenshot 2018-07-22 15 22 26" src="https://user-images.githubusercontent.com/1220911/43046026-61c3be18-8dc3-11e8-9f43-76a261f10996.png">

Current response

<img width="595" alt="screenshot 2018-07-22 15 19 00" src="https://user-images.githubusercontent.com/1220911/43046033-7882ba6e-8dc3-11e8-8556-64a9d8a2dea3.png">

cc: @clintwilson

**Comment by clintwilson** [comment]
The order details endpoint should return the server_platform object for that Order. This looks like a bug and I'll investigate why that's not showing up.

**Comment by abunashir** [comment]
Cool, thanks, Clint!

**Comment by abunashir** [comment]
Sweet, it seems to be working like a charm now, thanks @clintwilson, really appreciate your help :)
